### ISSUE TITLE
Does it support Node js lamda functions written using Typescript?

### ISSUE THREAD

**Issue by s1mrankaur** [thundra-io/thundra-vscode-issues#2]
Does this plugin support debugging .ts files? Any way to parse typescript for debugging lambda functions written using TypeScript?

**Comment by rwxdash** [comment]
Yes, you can debug your lambdas that are written in TypeScript and use the `.ts` files to put breakpoints. Already answered a similar question on how to do it at https://github.com/thundra-io/thundra-vscode-issues/issues/1#issuecomment-1053960145.
