### ISSUE TITLE
Thundra Debugger: connected to the broker, waiting for your function...

### ISSUE THREAD

**Issue by s1mrankaur** [thundra-io/thundra-vscode-issues#3]
It connects to the broker but keeps waiting for the function although the API gateway is being hit and the hander function is run.

**Comment by rwxdash** [comment]
Hey @s1mrankaur, there are a couple of things to check here. It sounds like your function doesn't have the correct environment setup. 

Have you followed the steps that are listed here, https://apm.docs.thundra.io/node.js/online-debugging and used the correct key as a debug token, i.e. https://apm.thundra.io/settings/debugger?
