### ISSUE TITLE
Does it handle multiple lambdas, versions, and aliases?

### ISSUE THREAD

**Issue by agworkscode** [thundra-io/thundra-vscode-issues#4]
Title should say all. 

Can thundra handle debugging and setting breakpoints in multiple lambda functions in the same session?
Can it handle debugging specific versions or aliases of a lambda function?

**Comment by rwxdash** [comment]
Hey @agworkscode, thanks for opening the issue. 

Yes, it can handle multiple lambdas in the same session. To make it work, you'd have to give different session names for each lambda via the environment variable `THUNDRA_AGENT_LAMBDA_DEBUGGER_SESSION_NAME` and start multiple session on VSCode with a matching session name using the `Start Debugger (with a session name)` command.

Let us know if you have any other question.
